[workspace]
members = ["packages/*"]
exclude = ["contracts"]

resolver = "2"

[workspace.package]
version = "3.0.3-dev"

[workspace.dependencies]
cosmwasm-core = { path = "../ZK/cw/zk-cosmwasm/packages/core" }
cosmwasm-crypto = { path = "../ZK/cw/zk-cosmwasm/packages/crypto" }
cosmwasm-derive = { path = "../ZK/cw/zk-cosmwasm/packages/derive" }
cosmwasm-schema = { path = "../ZK/cw/zk-cosmwasm/packages/schema" }
cosmwasm-schema-derive = { path = "../ZK/cw/zk-cosmwasm/packages/schema-derive" }
cosmwasm-std = { path = "../ZK/cw/zk-cosmwasm/packages/std" }
cosmwasm-vm = { path = "../ZK/cw/zk-cosmwasm/packages/vm" }
zk-cosmwasm = { path = "../ZK/cw/zk-cosmwasm/packages/zk" }
cosmwasm-vm-derive = { path = "./packages/vm-derive" }
cw-schema = { path = "../ZK/cw/zk-cosmwasm/packages/cw-schema" }
cw-schema-derive = { path = "../ZK/cw/zk-cosmwasm/packages/cw-schema-derive" }
schemars = "0.8.4"
serde = { version = "1.0.192", default-features = false, features = ["alloc", "derive"] }
serde_json = "1.0.140"
thiserror = "1.0.26"

zk-test-press = { path = "../ZK/terp-rs/crates/zk/headstash/test-press" }