//! Norick: a witnessed string does not contain the work "rick"
//! The circuit is designed to work without knowing the specific private or public inputs during key generation.
//! During key generation, use NoRickCircuit::default() or call without_witnesses() on an instance, which sets priv_input to unknown values.
//! The forbidden string is loaded from the instance column, and since instance values are not needed for key generation (only for proving/verification),
//!  the circuit configures and synthesizes correctly with unknown instances.For proving, instantiate the circuit with the actual private inputs and provide
//!  the public inputs (including the forbidden string) to the prover.
//!
//! This matches standard Halo2 patterns where the circuit struct holds witness data for proving, but key generation uses placeholders.
//!

use group::ff::{Field, PrimeField};
use halo2_proofs::{
    circuit::{AssignedCell, Chip, Layouter, Region, SimpleFloorPlanner, Value},
    plonk::{self, Advice, Circuit, Column, ConstraintSystem, Error, Fixed, Instance, Selector},
    poly::Rotation,
    transcript::{Blake2bRead, Blake2bWrite},
};
use pasta_curves::{pallas, vesta, Fp};
use rand::RngCore;

use std::{
    eprintln,
    fs::File,
    io::{self, BufWriter, Write},
    marker::PhantomData,
    path::PathBuf,
    println,
    string::String,
    vec::Vec,
};

// ANCHOR: instructions
trait NumericInstructions<F: PrimeField>: Chip<F> {
    /// Variable representing a number.
    type Num;

    /// Loads a number into the circuit as a private input.
    fn load_private(&self, layouter: impl Layouter<F>, a: Value<F>) -> Result<Self::Num, Error>;

    /// Loads a number into the circuit as a fixed constant.
    fn load_constant(&self, layouter: impl Layouter<F>, constant: F) -> Result<Self::Num, Error>;

    /// Loads a number from public instance.
    fn load_public(&self, layouter: impl Layouter<F>, row: usize) -> Result<Self::Num, Error>;

    /// Returns `c = a * b`.
    fn mul(
        &self,
        layouter: impl Layouter<F>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error>;

    /// Exposes a number as a public input to the circuit.
    fn expose_public(
        &self,
        layouter: impl Layouter<F>,
        num: Self::Num,
        row: usize,
    ) -> Result<(), Error>;
}
// ANCHOR_END: instructions

// ANCHOR: chip
/// The chip that will implement our instructions! Chips store their own
/// config, as well as type markers if necessary.
#[derive(Debug)]
pub struct FieldChip<F: Field> {
    config: FieldConfig,
    _marker: PhantomData<F>,
}
// ANCHOR_END: chip

// ANCHOR: chip-config
/// Chip state is stored in a config struct. This is generated by the chip
/// during configuration, and then stored inside the chip.
#[derive(Clone, Debug)]
pub struct FieldConfig {
    /// For this chip, we will use two advice columns to implement our instructions.
    /// These are also the columns through which we communicate with other parts of
    /// the circuit.
    advice: [Column<Advice>; 2],

    /// This is the public input (instance) column.
    instance: Column<Instance>,

    // We need a selector to enable the multiplication gate, so that we aren't placing
    // any constraints on cells where `NumericInstructions::mul` is not being used.
    // This is important when building larger circuits, where columns are used by
    // multiple sets of instructions.
    s_mul: Selector,
}

impl<F: Field> FieldChip<F> {
    fn construct(config: <Self as Chip<F>>::Config) -> Self {
        Self {
            config,
            _marker: PhantomData,
        }
    }

    fn configure(
        meta: &mut ConstraintSystem<F>,
        advice: [Column<Advice>; 2],
        instance: Column<Instance>,
        constant: Column<Fixed>,
    ) -> <Self as Chip<F>>::Config {
        meta.enable_equality(instance);
        meta.enable_constant(constant);
        for column in &advice {
            meta.enable_equality(*column);
        }
        let s_mul = meta.selector();
        // Define our multiplication gate!
        meta.create_gate("mul", |meta| {
            // To implement multiplication, we need three advice cells and a selector
            // cell. We arrange them like so:
            //
            // | a0  | a1  | s_mul |
            // |-----|-----|-------|
            // | lhs | rhs | s_mul |
            // | out |     |       |
            //
            // Gates may refer to any relative offsets we want, but each distinct
            // offset adds a cost to the proof. The most common offsets are 0 (the
            // current row), 1 (the next row), and -1 (the previous row), for which
            // `Rotation` has specific constructors.
            let lhs = meta.query_advice(advice[0], Rotation::cur());
            let rhs = meta.query_advice(advice[1], Rotation::cur());
            let out = meta.query_advice(advice[0], Rotation::next());
            let s_mul = meta.query_selector(s_mul);

            // Finally, we return the polynomial expressions that constrain this gate.
            // For our multiplication gate, we only need a single polynomial constraint.
            //
            // The polynomial expressions returned from `create_gate` will be
            // constrained by the proving system to equal zero. Our expression
            // has the following properties:
            // - When s_mul = 0, any value is allowed in lhs, rhs, and out.
            // - When s_mul != 0, this constrains lhs * rhs = out.
            vec![s_mul * (lhs * rhs - out)]
        });

        FieldConfig {
            advice,
            instance,
            s_mul,
        }
    }
    fn constrain_equal(
        &self,
        mut layouter: impl Layouter<F>,
        a: &AssignedCell<F, F>,
        b: &AssignedCell<F, F>,
    ) -> Result<(), Error> {
        layouter.assign_region(
            || "constrain equal",
            |mut region| region.constrain_equal(a.cell(), b.cell()),
        )
    }
}
// ANCHOR_END: chip-config

// ANCHOR: chip-impl
impl<F: Field> Chip<F> for FieldChip<F> {
    type Config = FieldConfig;
    type Loaded = ();

    fn config(&self) -> &Self::Config {
        &self.config
    }

    fn loaded(&self) -> &Self::Loaded {
        &()
    }
}
// ANCHOR_END: chip-impl

// ANCHOR: instructions-impl
/// A variable representing a number.
#[derive(Clone)]
struct Number<F: PrimeField>(AssignedCell<F, F>);

impl<F: PrimeField> NumericInstructions<F> for FieldChip<F> {
    type Num = Number<F>;

    fn load_private(
        &self,
        mut layouter: impl Layouter<F>,
        value: Value<F>,
    ) -> Result<Self::Num, Error> {
        let config = self.config();

        layouter.assign_region(
            || "load private",
            |mut region| {
                region
                    .assign_advice(|| "private input", config.advice[0], 0, || value)
                    .map(Number)
            },
        )
    }

    fn load_constant(
        &self,
        mut layouter: impl Layouter<F>,
        constant: F,
    ) -> Result<Self::Num, Error> {
        let config = self.config();

        layouter.assign_region(
            || "load constant",
            |mut region| {
                region
                    .assign_advice_from_constant(|| "constant value", config.advice[0], 0, constant)
                    .map(Number)
            },
        )
    }

    fn load_public(&self, mut layouter: impl Layouter<F>, row: usize) -> Result<Self::Num, Error> {
        let config = self.config();

        layouter.assign_region(
            || "load public",
            |mut region| {
                region
                    .assign_advice_from_instance(
                        || "public input",
                        config.instance,
                        row,
                        config.advice[0],
                        0,
                    )
                    .map(Number)
            },
        )
    }

    fn mul(
        &self,
        mut layouter: impl Layouter<F>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error> {
        let config = self.config();

        layouter.assign_region(
            || "mul",
            |mut region: Region<'_, F>| {
                // We only want to use a single multiplication gate in this region,
                // so we enable it at region offset 0; this means it will constrain
                // cells at offsets 0 and 1.
                config.s_mul.enable(&mut region, 0)?;

                // The inputs we've been given could be located anywhere in the circuit,
                // but we can only rely on relative offsets inside this region. So we
                // assign new cells inside the region and constrain them to have the
                // same values as the inputs.
                a.0.copy_advice(|| "lhs", &mut region, config.advice[0], 0)?;
                b.0.copy_advice(|| "rhs", &mut region, config.advice[1], 0)?;

                // Now we can assign the multiplication result, which is to be assigned
                // into the output position.
                let value = a.0.value().copied() * b.0.value();

                // Finally, we do the assignment to the output, returning a
                // variable to be used in another part of the circuit.
                region
                    .assign_advice(|| "lhs * rhs", config.advice[0], 1, || value)
                    .map(Number)
            },
        )
    }

    fn expose_public(
        &self,
        mut layouter: impl Layouter<F>,
        num: Self::Num,
        row: usize,
    ) -> Result<(), Error> {
        let config = self.config();

        layouter.constrain_instance(num.0.cell(), config.instance, row)
    }
}
// ANCHOR_END: instructions-impl

// ANCHOR: circuit
/// The full circuit implementation.
///
/// In this struct we store the private input variables. We use `Option<F>` because
/// they won't have any value during key generation. During proving, if any of these
/// were `None` we would get an error.
#[derive(Debug)]
// #[cosmwasm_vm_derive::cosmwasm_circuit(i = 3)]

pub struct NoRickCircuit<F: PrimeField> {
    /// Fixed length of 20
    pub priv_input: Vec<Value<F>>,
}

impl<F: PrimeField> Default for NoRickCircuit<F> {
    fn default() -> Self {
        Self {
            priv_input: vec![Value::unknown(); 20],
        }
    }
}

impl<F: PrimeField> Circuit<F> for NoRickCircuit<F> {
    type Config = FieldConfig;
    type FloorPlanner = SimpleFloorPlanner;

    fn without_witnesses(&self) -> Self {
        Self::default()
    }

    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Config {
        eprintln!("📋 NoRickCircuit::configure called - THIS SHOULD ALWAYS RUN");
        let advice = [meta.advice_column(), meta.advice_column()];
        let instance = meta.instance_column();
        let constant = meta.fixed_column();
        FieldChip::configure(meta, advice, instance, constant)
    }

    fn synthesize(
        &self,
        config: Self::Config,
        mut layouter: impl Layouter<F>,
    ) -> Result<(), Error> {
        let chip = FieldChip::<F>::construct(config);
        // --------------------------------------------------------------
        // 2️⃣ Powers of 256 (little‑endian) – they are plain F values,
        //    no gates are needed to load them.
        // this essentially moves between 8-bit byte values
        // --------------------------------------------------------------
        let _pow_256_0 = F::from(256u64.pow(0)); // 256⁰
        let pow_256_1 = F::from(256u64.pow(1)); // 256¹
        let pow_256_2 = F::from(256u64.pow(2)); // 256² = 65536
        let pow_256_3 = F::from(256u64.pow(3)); // 256³ = 16777216

        // Load all private inputs
        let mut chars = Vec::new();
        for (i, &char_val) in self.priv_input.iter().enumerate() {
            let char_cell =
                chip.load_private(layouter.namespace(|| format!("load char {}", i)), char_val)?;
            chars.push(char_cell);
        }

        // ---------------------------------------------------------------------
        // Load forbidden word from instance row 0 (only 1 instance column now)
        let rick_constant = chip.load_public(layouter.namespace(|| "load public rick"), 0)?;
        // Check for "rick" at every possible starting index (0 to 16)
        let mut conditions = Vec::new();
        for idx in 0..17 {
            let c0 = chars[idx].clone();
            let c1 = chars[idx + 1].clone();
            let c2 = chars[idx + 2].clone();
            let c3 = chars[idx + 3].clone();

            // Compute differences from 'r','i','c','k'
            let packed_val = c0.0.value().copied()
                + c1.0.value().copied() * Value::known(pow_256_1)
                + c2.0.value().copied() * Value::known(pow_256_2)
                + c3.0.value().copied() * Value::known(pow_256_3);

            // ---- compute the difference from the packed constant “rick” ----------
            // `rick_const` is a `Number<F>` that we loaded earlier.
            let diff_val = packed_val - rick_constant.0.value().copied();

            // ---- turn the difference into a private cell (so we can multiply it) --
            let diff =
                chip.load_private(layouter.namespace(|| format!("diff {}", idx)), diff_val)?;

            conditions.push(diff);
        }

        // Compute product of all conditions
        let mut product = conditions[0].clone();
        for i in 1..conditions.len() {
            product = chip.mul(
                layouter.namespace(|| format!("mul conditions {}", i)),
                product,
                conditions[i].clone(),
            )?;
        }

        // Compute inverse of product (fails if product is zero)
        let inv_p_val = product.0.value().map(|p| p.invert().unwrap_or(F::ZERO));
        let inv_p = chip.load_private(layouter.namespace(|| "load inv_p"), inv_p_val)?;

        // Multiply product by its inverse; should be 1 if no match
        let product_times_inv =
            chip.mul(layouter.namespace(|| "product times inv"), product, inv_p)?;

        // Load constant 1
        let one = chip.load_constant(layouter.namespace(|| "load one"), F::ONE)?;
        // Constrain product_times_inv to equal 1 by binding both to the same instance cell
        chip.constrain_equal(
            layouter.namespace(|| "enforce product_times_inv == 1"),
            &product_times_inv.0,
            &one.0,
        )?;

        Ok(())
    }
}

/// Public inputs to the Headstash Action circuit.
#[derive(Clone, Debug)]
pub struct NoRickInstance {
    /// word we are proving private value does not contain
    pub word: String,
}

impl NoRickInstance {
    /// serialize instances into set of circuit field [vesta::Scalar] with lenth `I`
    pub fn to_halo2_instance(&self) -> [[vesta::Scalar; 1]; 1] {
        let mut instance = [vesta::Scalar::zero(); 1];
        instance[0] = str_to_field(&self.word);
        [instance]
    }
    /// serialize instances into set of circuit field bytes with lenth `I`,specifically for cosmwasm-std api
    pub fn to_cosmwasm_instance(&self) -> Vec<u8> {
        let instances = self.to_halo2_instance();
        let mut bytes = Vec::with_capacity(1 * 32);
        for instance_row in instances.iter() {
            for scalar in instance_row.iter() {
                // to_repr() returns a 32-byte little-endian representation
                bytes.extend_from_slice(scalar.to_repr().as_ref());
            }
        }
        bytes
    }
}

/// The proving key for the Orchard Action circuit.
#[derive(Debug)]
pub struct ProvingKey {
    params: halo2_proofs::poly::commitment::Params<vesta::Affine>,
    pk: plonk::ProvingKey<vesta::Affine>,
}

impl ProvingKey {
    /// Builds existing proving key
    pub fn new(
        pk: plonk::ProvingKey<vesta::Affine>,
        params: halo2_proofs::poly::commitment::Params<vesta::Affine>,
    ) -> Self {
        ProvingKey { params, pk }
    }
    /// Builds new proving key.
    pub fn build() -> Self {
        let params = halo2_proofs::poly::commitment::Params::new(10);
        let circuit: NoRickCircuit<pasta_curves::Fp> = Default::default();

        let vk = plonk::keygen_vk(&params, &circuit).unwrap();
        let pk = plonk::keygen_pk(&params, vk, &circuit).unwrap();

        ProvingKey { params, pk }
    }

    /// Builds pk & vk, writes to file
    pub fn build_and_write(path: PathBuf) -> io::Result<()> {
        let mut writer = BufWriter::new(File::create(path)?);
        let pk = Self::build();
        pk.params.write(&mut writer)?;
        pk.pk.get_vk().write(&mut writer)?;
        writer.flush()
    }

    /// retrieve a clone of the params
    pub fn params(&self) -> halo2_proofs::poly::commitment::Params<vesta::Affine> {
        self.params.clone()
    }
}

/// The verifying key for the Orchard Action circuit.
#[derive(Debug)]
pub struct VerifyingKey {
    /// params
    pub params: halo2_proofs::poly::commitment::Params<vesta::Affine>,
    /// vk
    pub vk: plonk::VerifyingKey<vesta::Affine>,
}

impl VerifyingKey {
    /// Builds the verifying key.
    pub fn new(vk: plonk::VerifyingKey<pasta_curves::EqAffine>) -> Self {
        let params = halo2_proofs::poly::commitment::Params::new(10);
        VerifyingKey { params, vk }
    }

    /// Builds the verifying key.
    pub fn build() -> Self {
        let params = halo2_proofs::poly::commitment::Params::new(10);
        let circuit: NoRickCircuit<pasta_curves::Fp> = Default::default();
        let vk = plonk::keygen_vk(&params, &circuit).unwrap();
        VerifyingKey { params, vk }
    }
}

/// A proof of the validity of an Orchard [`Bundle`].
///
/// [`Bundle`]: crate::bundle::Bundle
#[derive(Clone)]
pub struct Proof(Vec<u8>);

impl core::fmt::Debug for Proof {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        if f.alternate() {
            f.debug_tuple("Proof").field(&self.0).finish()
        } else {
            // By default, only show the proof length, not its contents.
            f.debug_tuple("Proof")
                .field(&format_args!("{} bytes", self.0.len()))
                .finish()
        }
    }
}

impl Proof {
    /// Constructs a new Proof value.
    pub fn new(bytes: Vec<u8>) -> Self {
        Proof(bytes)
    }
    /// clones copy of bytes a new Proof value.
    pub fn bytes(&self) -> Vec<u8> {
        self.0.clone()
    }

    /// Creates a proof for the given circuits and instances.
    pub fn create(
        pk: &ProvingKey,
        circuits: &[NoRickCircuit<pasta_curves::Fp>],
        instances: &[NoRickInstance],
        mut rng: impl RngCore,
    ) -> Result<Self, plonk::Error> {
        let instances: Vec<_> = instances.iter().map(|i| i.to_halo2_instance()).collect();
        let instances: Vec<Vec<_>> = instances
            .iter()
            .map(|i| i.iter().map(|c| &c[..]).collect())
            .collect();
        let instances: Vec<_> = instances.iter().map(|i| &i[..]).collect();

        let mut transcript = Blake2bWrite::<_, vesta::Affine, _>::init(vec![]);
        plonk::create_proof(
            &pk.params,
            &pk.pk,
            circuits,
            &instances,
            &mut rng,
            &mut transcript,
        )?;
        Ok(Proof(transcript.finalize()))
    }

    /// Verifies this proof with the given instances.
    pub fn verify(
        &self,
        vk: &VerifyingKey,
        instances: &[NoRickInstance],
    ) -> Result<(), plonk::Error> {
        let instances: Vec<_> = instances.iter().map(|i| i.to_halo2_instance()).collect();
        let instances: Vec<Vec<_>> = instances
            .iter()
            .map(|i| i.iter().map(|c| &c[..]).collect())
            .collect();
        let instances: Vec<_> = instances.iter().map(|i| &i[..]).collect();

        let strategy = plonk::SingleVerifier::new(&vk.params);
        let mut transcript = Blake2bRead::init(&self.0[..]);
        plonk::verify_proof(&vk.params, &vk.vk, strategy, &instances, &mut transcript)
    }

    // /// Adds this proof to the given batch for verification with the given instances.
    // ///
    // /// Use this API if you want more control over how proof batches are processed. If you
    // /// just want to batch-validate Orchard bundles, use [`bundle::BatchValidator`].
    // ///
    // /// [`bundle::BatchValidator`]: crate::bundle::BatchValidator
    // pub fn add_to_batch(&self, batch: &mut BatchVerifier<vesta::Affine>, instances: Vec<Instance>) {
    //     let instances = instances
    //         .iter()
    //         .map(|i| {
    //             i.to_halo2_instance()
    //                 .into_iter()
    //                 .map(|c| c.into_iter().collect())
    //                 .collect()
    //         })
    //         .collect();

    //     batch.add_proof(instances, self.0.clone());
    // }
}

/// string to field
pub fn str_to_field<F: PrimeField>(s: &str) -> F {
    let mut repr = F::default().to_repr();
    let src = s.as_bytes();
    let len = core::cmp::min(src.len(), repr.as_ref().len());
    repr.as_mut()[..len].copy_from_slice(&src[..len]);
    F::from_repr(repr).expect("str_to_field")
}

// ANCHOR: dev-graph
#[test]
fn test_rick_circuit() {
    use halo2_proofs::dev::MockProver;
    use pasta_curves::Fp;
    let circuit_rows: u32 = 10;

    // Test with "ricky" (contains "rick") - should fail
    let s1 = "ricky";
    let s2 = "ronaldrickstien";
    let s3 = "randy";

    let as_bytes = s1.as_bytes();
    println!("s1 as_bytes: {:#?}", as_bytes);
    println!("s1 byte lens: {:#?}", as_bytes.len());
    let mut bytes1 = as_bytes.to_vec();
    bytes1.resize(20, 0);
    println!("resized 5 byte string to full 20 via padding");
    println!("bytes1.len(): {:#?}", bytes1.len());
    println!("bytes1: {:#?}", bytes1);

    let priv_input: Vec<Value<Fp>> = bytes1
        .iter()
        .map(|&b| Value::known(Fp::from(b as u64)))
        .collect();

    let mut circuit: NoRickCircuit<pallas::Base> = NoRickCircuit { priv_input };
    // === THE CONSTRAINT===:
    // set to 1 as we inverse constraint (if result == 0 , we know that the private input has "rick in it")
    let public_input = vec![str_to_field("rick")];

    let prover1 = MockProver::run(circuit_rows, &circuit, vec![public_input.clone()]).unwrap();
    assert!(prover1.verify().is_err());

    let mut bytes2 = s2.as_bytes().to_vec();
    println!("s2 as_bytes: {:#?}", bytes2);
    println!("s2 byte lens: {:#?}", bytes2.len());
    bytes2.resize(20, 0);
    println!("s2 resized byte lens: {:#?}", bytes2.len());
    println!("s2: {:#?}", bytes2);

    let string_vec2: Vec<Value<Fp>> = bytes2
        .iter()
        .map(|&b| Value::known(Fp::from(b as u64)))
        .collect();

    circuit.priv_input = string_vec2;

    let prover2 = MockProver::run(circuit_rows, &circuit, vec![public_input]).unwrap();
    assert!(prover2.verify().is_err());

    // Ensure we are not dropping any of the values
    let mut bytes3 = s3.as_bytes().to_vec();
    bytes3.resize(20, 0);

    let string_vec3: Vec<Value<Fp>> = bytes3
        .iter()
        .map(|&b| Value::known(Fp::from(b as u64)))
        .collect();

    circuit.priv_input = string_vec3;

    // Circuit now uses only 1 instance (the forbidden word at row 0)
    let public_inputs3 = vec![str_to_field("rick")];
    let prover3 = MockProver::run(circuit_rows, &circuit, vec![public_inputs3]).unwrap();
    assert!(prover3.verify().is_ok());
}
// ANCHOR_END: dev-graph
